apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recebimento-integracao-publicador-acl
  description: API genérica para criação de ACL de descida da SAP
  test: dtl_tribo_fin
  annotations:
    dev.azure.com/project-repo: Tribo Financeiro/recebimento-integracao-publicador-acl
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=recebimento-integracao-publicador-acl'
    backstage.io/source-location: 'url:https://dev.azure.com/localiza/Tribo Financeiro/_git/recebimento-integracao-publicador-acl'
    sonarqube.org/project-key: recebimento-integracao-publicador-acl
    kubecost/deployment: recebimento-integracao-publicador-acl
  embed:
    monitoring:
      title: "Monitoring"
      embeds:
        - type: iframe
          id: datadog-dotnet-apm
          label: Datadog - APM
          payload:
            url: https://p.datadoghq.com/sb/lop5xg5iuckc906z-84a12e0b998a7e649126f5da784546be
            queryString:
              tpl_var_env: prd
              tpl_var_service: recebimento-integracao-publicador-acl
              tpl_var_service-http-client: recebimento-integracao-publicador-acl-http-client
              live: true

        - type: grafana
          id: grafana-kubernetes-pods
          label: Grafana - Kubernetes PODs
          payload:
            dashboard: kubernetes-pods
            cluster: k8s-vanilla
            queryString:
              var-area: fi
              var-dominio: recebimento
              var-produto: acl

  links:
    - url: https://dev.azure.com/localiza/Tribo Financeiro/_git/recebimento-integracao-publicador-acl
      title: Repositório
      icon: info
    - url: https://dev.azure.com/localiza/Tribo Financeiro/_build?pipelineNameFilter=recebimento-integracao-publicador-acl
      title: Pipeline
      icon: info
    - url: https://sonarcloud.io/project/overview?id=recebimento-integracao-publicador-acl
      title: Sonar
      icon: info
    - url: https://monitoring-aws-np.localiza.dev/d/EMo-8KW4k/kubernetes-pods-backstage?orgId=1&refresh=1m&var-datasource=default&var-cluster=&var-area=ti&var-dominio=recebimento&var-produto=acl&var-application=recebimento-integracao-publicador-acl&var-ambiente=dev    
      title: Grafana dev
      icon: info
    - url: https://monitoring-aws-np.localiza.dev/d/EMo-8KW4k/kubernetes-pods-backstage?orgId=1&refresh=1m&var-datasource=default&var-cluster=&var-area=ti&var-dominio=recebimento&var-produto=acl&var-application=recebimento-integracao-publicador-acl&var-ambiente=tst    
      title: Grafana tst
      icon: info
    - url: https://monitoring-aws-prd.localiza.com/d/qAYz52MMz/kubernetes-pods-backstage?orgId=1&refresh=1m&var-datasource=default&var-cluster=&var-area=ti&var-dominio=recebimento&var-produto=acl&var-application=recebimento-integracao-publicador-acl&var-ambiente=prd    
      title: Grafana prd
      icon: info
    - url: "https://es-financeiro-np.localiza.dev/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24w,to:now))&_a=(columns:!(_source),filters:!(),interval:auto,query:(language:kuery,query:%22recebimento-integracao-publicador-acl%22),sort:!())"
      title: Kibana dev
      icon: info
    - url: "https://es-financeiro-prd.localiza.com/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-24w,to:now))&_a=(columns:!(_source),filters:!(),interval:auto,query:(language:kuery,query:%22recebimento-integracao-publicador-acl%22),sort:!())"
      title: Kibana prod
      icon: info
    - url: "https://dash-eks-financeiro-np.localiza.dev/#/search?namespace=fi-recebimento-acl-dev&q=recebimento-integracao-publicador-acl"
      title: Dashboard Kubernetes dev
      icon: info
    - url: "https://dash-eks-financeiro-np.localiza.dev/#/search?namespace=fi-recebimento-acl-tst&q=recebimento-integracao-publicador-acl"
      title: Dashboard Kubernetes tst
      icon: info
    - url: https://eks-financeiro-dev.localiza.dev/recebimento-integracao-publicador-acl/health
      title: Healthcheck dev
      icon: info
    - url: https://eks-financeiro-tst.localiza.dev/recebimento-integracao-publicador-acl/health
      title: Healthcheck tst
      icon: info
    - url: https://eks-financeiro-prd.localiza.com/recebimento-integracao-publicador-acl/health
      title: Healthcheck prd
      icon: info
    - url: https://eks-financeiro-dev.localiza.dev/recebimento-integracao-publicador-acl/swagger
      title: Swagger dev
      icon: info
    - url: https://eks-financeiro-tst.localiza.dev/recebimento-integracao-publicador-acl/swagger
      title: Swagger tst
      icon: info
    - url: https://b-343b5916-e74a-4b2b-9a05-9478bcb40f42.mq.us-east-1.amazonaws.com
      title: Console RabbitMq dev
      icon: info
    - url: https://b-a0d13eec-b258-4cd5-bfb5-550ed1f95232.mq.us-east-1.amazonaws.com
      title: Console RabbitMq prd
      icon: info
    - url: https://monitoring-aws-np.localiza.dev/d/9aHhVJM7k/rabbitmq-aws-tribo-financeiro?orgId=1&refresh=30s
      title: Grafana RabbitMq dev
      icon: info
    - url: https://monitoring-aws-prd.localiza.com/d/Msq7QOinz/rabbitmq-aws-tribo-financeiro?orgId=1&refresh=30s
      title: Grafana RabbitMq prd
      icon: info
    - url: https://app.datadoghq.com/apm/services/recebimento-integracao-publicador-acl/operations/aspnet_core.request
      title: Datadog webapi
      icon: info
    - url: https://app.datadoghq.com/dashboard/6c2-5yz-yie/localizafinanceiro---recebimento-integracao-publicador-acl
      title: Datadog Dashboard
      icon: info

spec:
  type: service
  lifecycle: experimental
  owner: dtl_tribo_fin
  dependsOn:
    - resource:default/rabbitmq-financeiro
    - resource:default/eks-financeiro
