trigger:
  branches:
    include:
      - '*'
    exclude:
      - 'master'
      - 'main'

resources:
  repositories:
    - repository: templatesconfig
      type: git
      name: 'Infraestrutura - Localiza Agile/TI.CICD.Configuration'
      ref: refs/heads/main
    - repository: templates
      type: git
      name: 'Infraestrutura - Localiza Agile/TI.CICD.Templates'
      ref: refs/tags/7-stable
    - repository: templatesbackstage
      type: git
      name: 'Infraestrutura - Localiza Agile/TI.CICD.Templates.Backstage'
      ref: refs/tags/2-stable
    - repository: mudanca
      type: git
      name: 'Infraestrutura/OPS.AzureDevOps.GestaoDeMudanca'
      ref: refs/tags/8-stable

parameters:
  - name: TechDocs
    default: "true"
    values:
      - true
      - false
# parametros de mudança
  - name: TipoDeMudanca
    default: "Normal"
    values:
      - Normal
      - Emergencial
      - Urgente
  - name: Categoria
    default: "Qualidade"
    values:
      - Conformidade
      - Estrategia
      - Financeiro
      - Produtividade
      - Qualidade
  - name: Risco
    default: Low
    values:
      - Low
      - Moderate
      - High
  - name: TituloDaMudanca
    default: "Publicação de CDC Worker"
  - name: DescricaoDetalhadaDaMudanca
    default: "(Verificar opcoes validas no ServiceNow)"
  - name: GrupoDeAtribuicao
    default: "Squad TECH - Integrações Digitais"
  - name: Impacto
    default: "1 - High"
    values:
      - "1 - High"
      - "2 - Medium"
      - "3 - Low"
  - name: Indisponibilidade
    default: "no"
    values:
      - "yes"
      - "no"
  - name: InicioPlanejado
    default: "dd-mm-aaaa hh:mm:ss"
  - name: FimPlanejado
    default: "dd-mm-aaaa hh:mm:ss"
  - name: IncidenteOuProblema
    default: '(Apenas p/ Emerg ou corretiva) Ex: INC000000'
  - name: PrioridadeDoIncidenteOuProblema
    default: '1 - High'
    values:
      - 1 - High
      - 2 - Medium
      - 3 - Low
      - (Apenas p/ emergencial ou corretiva)
  - name: Justificativa
    default: '(Apenas p/ Urgentes)'
  - name: UriAnexo
    default: '(Apenas p/ Urgentes - Apenas HTTPS)'
  - name: Motivo
    default: "Requisitos de negócios"
  - name: NecessidadeAlteracaoAmbiente
    default: '(Apenas se variavel Motivo for igual a Outro)'
  - name: EfeitoDeNaoPublicacao
    default: "Não será possível descomissionar o TIBCO."
  - name: AnaliseDeRiscoEImpacto
    default: "(Verificar opcoes validas no ServiceNow)"
  - name: PlanoDeTeste
    default: "(Verificar opcoes validas no ServiceNow)"
  - name: Natureza
    default: "Evolutiva"
    values:
      - Corretiva
      - Evolutiva
      - Preventiva
      - Regulamentar
      - Roll Forward
  - name: PlanoDeMudanca
    default: "(Verificar opcoes validas no ServiceNow)"
  - name: PlanoDeRetorno
    default: "(Verificar opcoes validas no ServiceNow)"
  - name: DuracaoDoPlanoDeRetorno
    default: "00:30:00"
  - name: UtilizadoAppDynamicsOuDatadog
    default: "true"
    values:
      - true
      - false
  - name: MotivoNaoUtilizarAppDynamicsOuDatadog
    default: '(Apenas se UtilizadoAppDynamicsOuDatadog for false)'
  - name: Monitoramento
    default: '(Apenas p/ aplicacoes monitoradas)'
  - name: LoginDeRedeTerceiro
    default: '(Apenas p/ terceiros) Ex: 191032'

variables:
  # pipeline variables
  - name: CadeiaValor
    value: cadeia-valor-padrao
  - name: Area
    value: ti
  - name: Dominio
    value: integracoes-digitais
  - name: Tribo
    value: tech products
  - name: Squad
    value: integracoes digitais
  - name: Produto
    value: cdcworker-agaddressen-pub 
  - name: AppLanguage
    value: netcore
  - name: AppVersion
    value: 1.11.0
  - name: ChartName
    value: netcore30-web
  - name: ChartVersion
    value: 2.8
  - name: Secrets
    value: DB-INTEG-DIGIT-SYBASE-RABBIT-SYB,redis-aws-tribo-tech-products-compartilhado,kafka-tech-products-integracoes-digitais-integracoes-digitais-cdc
  - name: PlataformaMonitoramento
    value: datadog
  - name: CPCodeDev
    value:
  - name: CPCodeTst
    value:
  - name: CPCodeStg
    value:
  - name: CPCodePrd
    value:
  - name: Lab
    value: backend
  - name: Criticidade
    value: baixa

# variaveis mudanca       -- ATENCAO Não mude os valores das variáveis associadas a parametros - Ajuste o item de configuracao
  - name: 01-TipoDeMudanca
    value: ${{ parameters.TipoDeMudanca }}
  - name: 02-Categoria
    value: ${{ parameters.Categoria }}
  - name: 03-Risco
    value: ${{ parameters.Risco }}
  - name: 04-TituloDaMudanca
    value: ${{ parameters.TituloDaMudanca }}
  - name: 05-DescricaoDetalhadaDaMudanca
    value: ${{ parameters.DescricaoDetalhadaDaMudanca }}
  - name: 06-GrupoDeAtribuicao
    value: ${{ parameters.GrupoDeAtribuicao }}
  - name: 07-Impacto
    value: ${{ parameters.Impacto }}
  - name: 08-Indisponibilidade
    value: ${{ parameters.Indisponibilidade }}
  - name: 09-InicioPlanejado
    value: ${{ parameters.InicioPlanejado }}
  - name: 10-FimPlanejado
    value: ${{ parameters.FimPlanejado }}
  - name: 11-IncidenteOuProblema
    value: ${{ parameters.IncidenteOuProblema }}
  - name: 12-PrioridadeDoIncidenteOuProblema
    value: ${{ parameters.PrioridadeDoIncidenteOuProblema }}
  - name: 13-Justificativa
    value: ${{ parameters.Justificativa }}
  - name: 14-UriAnexo
    value: ${{ parameters.UriAnexo }}
  - name: 15-Motivo
    value: ${{ parameters.Motivo }}
  - name: 16-NecessidadeAlteracaoAmbiente
    value: ${{ parameters.NecessidadeAlteracaoAmbiente }}
  - name: 17-EfeitoDeNaoPublicacao
    value: ${{ parameters.EfeitoDeNaoPublicacao}}
  - name: 18-AnaliseDeRiscoEImpacto
    value: ${{ parameters.AnaliseDeRiscoEImpacto}}
  - name: 19-PlanoDeTeste
    value: ${{ parameters.PlanoDeTeste }}
  - name: 20-Natureza
    value: ${{ parameters.Natureza }}
  - name: 21-PlanoDeMudanca
    value: ${{ parameters.PlanoDeMudanca }}
  - name: 22-PlanoDeRetorno
    value: ${{ parameters.PlanoDeRetorno }}
  - name: 23-DuracaoDoPlanoDeRetorno
    value: ${{ parameters.DuracaoDoPlanoDeRetorno }}
  - name: 24-UtilizadoAppDynamicsOuDatadog
    value: ${{ parameters.UtilizadoAppDynamicsOuDatadog }}
  - name: 25-MotivoNaoUtilizarAppDynamicsOuDatadog
    value: ${{ parameters.MotivoNaoUtilizarAppDynamicsOuDatadog }}
  - name: 26-Monitoramento
    value: ${{ parameters.Monitoramento }}
  - name: LoginDeRedeTerceiro
    value: ${{ parameters.LoginDeRedeTerceiro }}
  - name: ItemConfiguracao
    value: cdcworker-agaddressen-pub

  - template: config.yml@templatesconfig
  - template: yaml/config/vars.yml@templates

stages:
  # - template: yaml/pipelines/pipeline-k8s-harness.yml@templates    #  HARNESS => habilita o CD pelo Harness
  - template: yaml/pipelines/pipeline-k8s.yml@templates
    parameters:
      FerramentaDeDeploy: azure-devops               # azure-devops ou harness
      ClusterKubernetesNP: $(ClusterAWSTechProductsNP)
      ClusterKubernetesPRD: $(ClusterAWSTechProductsPRD)
      FrameworkBuildTeste: netcore
      netCoreVersion: '8.x'
      TechDocs:
        enabled: ${{ parameters.TechDocs }}
        dev: true
        prd: true
      Ambientes:
        dev:
          DeployFeature: false
          EstrategiaDeDeploy: rolling    # HARNESS => rolling, canary ou blue-green
#          ContinuousVerification:        # HARNESS => se desejar Continuous verification pos deploy defaultt  true para todos
#            DataDogMetrics: true
#            DataDogLogs: true
#            Prometheus: true
#            ELK: true
#          Testes:
#            - Tipo: Componente
#              Imagem: nunit
        tst:
          EstrategiaDeDeploy: rolling    # HARNESS => rolling, canary ou blue-green
#          ContinuousVerification:        # HARNESS => se desejar Continuous verification pos deploy defaultt  true para todos
#            DataDogMetrics: true
#            DataDogLogs: true
#            Prometheus: true
#            ELK: true
#          Testes:
#            - Tipo: Carga
#              Imagem: gatling
#            - Tipo: EndToEnd
#              Imagem: nunit
#            - Tipo: Integracao
#              Imagem: nunit
#            - Tipo: Mutante
#              Imagem: netcore-3/x-stryker
#              Depende:
#                - Carga
#                - EndToEnd
        stg: false
        prd:
          EstrategiaDeDeploy: rolling    # HARNESS => rolling, canary ou blue-green
      K8sMaintenance:
        enabled: false
        dev:
          enabled: true
          RestartApplication: true
        tst:
          enabled: true
          RestartApplication: true
        prd:
          enabled: true
          RestartApplication: true
      Harness:
        CanaryInstancePercent: "20"             # Se EstrategiaDeDeploy informe a porcentagem de 0 a 100
        PipelineVersion: "7-stable"             # Versão da pipeline
